services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    ports:
      - "8125:8125/udp"
      - "8125:8125/tcp"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
